# Generated by Django 5.0.4 on 2024-05-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
